_target_: adjoint_sampling.energies.fairchem_energy.FairChemEnergy
tau: ${tau}  # Temperature parameter 
alpha: ${alpha}  # bond structure regularizing energy
device: ${device}  # Device to run training on
# _partial_: True